### ISSUE TITLE
Create Google Sheets graphs

### ISSUE THREAD

**Issue by Inventitech** [lacinoire/master-thesis#23]

**Comment by Inventitech** [comment]
See graphs in `img/lit-sur` and Google Sheet. Do we have graphs of all the things we want to report on? Anything to improve?

**Comment by lacinoire** [comment]
They look super nice 😄
general & minor:
if you want and touch them again (for other reasons) you can try to take out as much white from top/bottom as possible → take less space and we have more for text

use:
„Classification“ should move over to „kind of retrieved“ and be removed here
if you touch this again:
only if you revisit this one again:
the lines are broader in this graph, could be compacted (vertically) → uniformness + resulting graph will take up less space

kind of retrieved: and name of implementation:
we have no graph, but I also think we don’t need one
I've described the results without a graph

source of logs:
travis / travistorrent / industrial
**I think we might want one here**
to support we are using travis logs for our eval

**Comment by Inventitech** [comment]
Re the space (to the left) of the figures, this is so they can aligned and have the same size (hopefully).

Don't think I understand the other comments, but happy to take a second look
