### ISSUE TITLE
Make Graphic: Log Diversity

### ISSUE THREAD

**Issue by lacinoire** [lacinoire/master-thesis#27]
![grafik](https://user-images.githubusercontent.com/15169604/78349104-5c7c7200-75a3-11ea-968a-685e6472438e.png)
maven, java explizit erwähnen, wie viele andere tools die nur einmal erwähnt wurden

**Comment by Inventitech** [comment]
Intentionally assigned  to me?

**Comment by lacinoire** [comment]
Yes, though I can also do this one together with the overview graphics
the style / way of creating is closer to the overview graphics than the google sheet ones 😄

**Comment by Inventitech** [comment]
I'll propose something

**Comment by Inventitech** [comment]
This looks suitable to me: 

[chart.pdf](https://github.com/lacinoire/master-thesis/files/4438299/chart.pdf)

Do you want to give it a shot at trying to label the two areas of the graph?

**Comment by Inventitech** [comment]
(latest graph in repository)

**Comment by Inventitech** [comment]
Maybe you find a nice way to annotate the graph without it looking 'authoritative' (for which we do not have the data)

**Comment by lacinoire** [comment]
> This looks suitable to me:
> 
> [chart.pdf](https://github.com/lacinoire/master-thesis/files/4438299/chart.pdf)
> 
> Do you want to give it a shot at trying to label the two areas of the graph?

very good idea 👍🏼
