### ISSUE TITLE
Write 200 word novelty statement

### ISSUE THREAD

**Issue by lacinoire** [lacinoire/master-thesis#38]
From the TSE authoring guidelines:

Authors of “Journal First” manuscripts will be required to submit a 200-word statement that attests to the novelty of their work relative to these criteria.

**Comment by Inventitech** [comment]
Paper contribution list can help in writing this

**Comment by Inventitech** [comment]
- first lit survey on the topic
- first reference implementation of three techniques
- first comparison of techniques ...
